// L’archipel : les paysages. Choisis par la personne quand elle commence une île.
// Un paysage ne dit rien : il change les couleurs du sol, les essences, les maisons, les cultures, le petit décor,
// et la vie qui se promène (vie.js) : des bêtes par paysage, [espèce, nombre, couleurs pour les papillons].
// escarpe : la part de falaises sur le rivage, en plus ou en moins (monde.js). oiseaux : ceux du ciel, [espèce, nombre].
// Ce qui dit quelque chose reste la famille, l’espèce, la taille et l’état (grammaire.js).

export const BIOMES = {
  prairie: {
    nom: 'la prairie', dit: 'des herbes, des pâquerettes, des toits rouges',
    sol: { herbe: ['#a9db60', '#8fc74b', '#76b03c'], sable: ['#f3e3b4', '#e8d49f', '#d9c28a'], roche: ['#bcb4a8', '#a49b8e', '#8a8175'], neige: ['#ffffff', '#f1f4f7', '#dde3e8'] },
    taches: ['#c9e27a', .16], falaise: ['#a07752', '#7f5c3d'],
    eau: null, lagon: '200,248,242',
    feuillu: { formes: ['rond', 'etage', 'peuplier'], tons: [['#b4e66a', '#84c94a', '#5f9e34'], ['#9fdc6e', '#72bd4c', '#4f9638'], ['#c3e57a', '#96c854', '#6fa33c']] },
    fleuri: { formes: ['rond', 'etage'], tons: [['#ffe1ea', '#f7b3c8', '#df8fab'], ['#fff7f2', '#f3dcd6', '#dcbdb5']] },
    pin: { formes: ['sapin', 'elance', 'cypres'], tons: [['#4f9e66', '#357a4d', '#25593a']] },
    maisons: { murs: [['#f6eddb', '#dccfb5'], ['#efe6d6', '#d4c8b2']], toits: [['#dc6a52', '#b4503c'], ['#e38b5c', '#bd6b42']], styles: ['colombage', 'pierre', 'crepi'] },
    champs: ['ble', 'potager', 'ble'],
    decor: { herbe: [['touffe', 5], ['paquerette', 3], ['bouton', 2], ['trefle', 2], ['dalle', 1], ['buisson', 2], ['buissonfleuri', 1]], sable: [['galet', 3], ['touffe', 1], ['rocher', 1]], roche: [['eclat', 2], ['mousse', 2], ['rocher', 2]], neige: [['eclat', 1]] },
    vie: [['mouton', 3], ['poule', 2], ['papillon', 3, ['#ffd166', '#ffffff', '#ff9ecf', '#b08cff']]],
    oiseaux: [['mouette', 3]],
    densite: .62, mousse: true,
  },
  automne: {
    nom: 'la forêt d’automne', dit: 'des feuilles rousses, des champignons, des souches',
    sol: { herbe: ['#c9c36c', '#b1ab55', '#958f41'], sable: ['#f1dfb2', '#e6d09c', '#d6bd86'], roche: ['#b9ae9f', '#9f9383', '#857a6b'], neige: ['#ffffff', '#f1f4f7', '#dde3e8'] },
    taches: ['#e59a4c', .3], falaise: ['#9a6e4c', '#7a543a'],
    eau: '#5aa6c2', lagon: '205,240,232',
    feuillu: { formes: ['rond', 'etage', 'etage'], tons: [['#ffb04a', '#f08a2c', '#c9661e'], ['#ff8a5c', '#e5603a', '#b8452a'], ['#ffd86a', '#f2b93e', '#cc9328'], ['#d8e070', '#b2bf4c', '#8a9638']] },
    fleuri: { formes: ['rond'], tons: [['#ffe6d6', '#f6c0a4', '#dd9a7c']] },
    pin: { formes: ['sapin', 'elance'], tons: [['#5b8f5a', '#406f43', '#2c5231']] },
    maisons: { murs: [['#f3e7d2', '#d8c9ae'], ['#e9dcc6', '#cdbd9f']], toits: [['#b8584a', '#8e4136'], ['#7f8fa3', '#626f80']], styles: ['colombage', 'bois', 'pierre'] },
    champs: ['citrouilles', 'ble'],
    decor: { herbe: [['feuilles', 6], ['champignon', 3], ['touffe', 2], ['souche', 1], ['buche', 1], ['buisson', 2]], sable: [['galet', 2], ['feuilles', 1], ['rocher', 1]], roche: [['mousse', 2], ['champignon', 1], ['eclat', 1], ['rocher', 2]], neige: [['eclat', 1]] },
    vie: [['renard', 1], ['poule', 2], ['papillon', 1, ['#f2b93e', '#fff1c1']]],
    oiseaux: [['oie', 5], ['mouette', 1]],
    densite: .7, mousse: true, feuillesNues: true,
  },
  tropique: {
    nom: 'l’île tropicale', dit: 'des palmiers, du sable blanc, un lagon',
    sol: { herbe: ['#86dc5a', '#68c448', '#50a83c'], sable: ['#fff3d6', '#f7e6ba', '#ecd49c'], roche: ['#cdbb9f', '#b3a085', '#98866c'], neige: ['#ffffff', '#f1f4f7', '#dde3e8'] },
    taches: ['#a6ec78', .12], falaise: ['#c09268', '#9c7250'], escarpe: -.2, // surtout des plages
    eau: '#2fd0d4', lagon: '170,255,238',
    feuillu: { formes: ['palmier', 'palmier', 'rond'], tons: [['#8ee06a', '#5cc04a', '#3f9a3a']] },
    fleuri: { formes: ['hibiscus'], tons: [['#8ee06a', '#5cc04a', '#3f9a3a']] },
    pin: { formes: ['elance', 'cypres'], tons: [['#3f9a5a', '#2b7a45', '#1d5a33']] },
    maisons: { murs: [['#e2bd86', '#c29a66'], ['#f4e6cc', '#d8c6a4']], toits: [['#e8c870', '#c8a64c']], styles: ['paillote', 'bois'] },
    champs: ['riz', 'ananas'],
    decor: { herbe: [['fougere', 4], ['fleurrouge', 2], ['touffe', 2], ['buisson', 2], ['buissonfleuri', 1]], sable: [['coquillage', 3], ['galet', 1], ['etoile', 1], ['rocher', 1]], roche: [['eclat', 1], ['fougere', 1], ['rocher', 2]], neige: [['eclat', 1]] },
    vie: [['crabe', 3], ['papillon', 3, ['#ff4d6d', '#ffd166', '#5fd3ff']], ['poule', 1]],
    oiseaux: [['fregate', 3]],
    densite: .55, mousse: false,
  },
  neige: {
    nom: 'l’île enneigée', dit: 'de la neige, des sapins, des fenêtres chaudes',
    sol: { herbe: ['#fbfdff', '#eaf1f7', '#d6e2ec'], sable: ['#e3e9ef', '#d2dbe4', '#c0cbd6'], roche: ['#b4bec9', '#97a2ae', '#7c8793'], neige: ['#ffffff', '#f6f9fc', '#e6edf3'] },
    taches: ['#dfe9f4', .22], falaise: ['#8d949e', '#6f7680'],
    eau: '#86b4cc', lagon: '228,242,252',
    feuillu: { formes: ['rond', 'etage'], tons: [['#f4fafd', '#d5e7f0', '#afcbdc']] },
    fleuri: { formes: ['rond'], tons: [['#ffe8f0', '#f2c3d4', '#d99db2']] },
    pin: { formes: ['sapin', 'elance', 'sapin'], tons: [['#4a7f6a', '#335f50', '#244639']] },
    maisons: { murs: [['#9a6446', '#7a4c34'], ['#ece4d8', '#d0c6b6']], toits: [['#5f7fa3', '#48637f'], ['#8a4a3c', '#6c3a2f']], styles: ['bois', 'crepi'] },
    champs: ['neige'],
    decor: { herbe: [['tasneige', 4], ['baies', 2], ['eclat', 1], ['sapineau', 1], ['buisson', 1], ['rocher', 1]], sable: [['tasneige', 2], ['galet', 1]], roche: [['eclat', 2], ['tasneige', 1], ['rocher', 2]], neige: [['tasneige', 1]] },
    vie: [['rougegorge', 2], ['lievre', 1]],
    oiseaux: [['goeland', 2]],
    densite: .5, mousse: false, enneige: true,
  },
  lande: {
    nom: 'la lande', dit: 'de la bruyère, des bouleaux, des toits d’ardoise',
    sol: { herbe: ['#a3be70', '#8aa65c', '#71894a'], sable: ['#ebdfc4', '#ddcfb0', '#cbbc9a'], roche: ['#aaa9a1', '#8f8e87', '#75746e'], neige: ['#ffffff', '#f1f4f7', '#dde3e8'] },
    taches: ['#a57dc4', .26], falaise: ['#8c7058', '#6c5644'], escarpe: .18, // surtout des falaises
    eau: '#5f9fb6', lagon: '205,236,240',
    feuillu: { formes: ['bouleau', 'bouleau', 'rond'], tons: [['#b7d98a', '#94bd66', '#739c4c']] },
    fleuri: { formes: ['rond'], tons: [['#eadcf7', '#cdb3ea', '#a88bcf']] },
    pin: { formes: ['cypres', 'sapin'], tons: [['#5a8a62', '#3f6a4a', '#2c4f36']] },
    maisons: { murs: [['#d3cec4', '#b6b0a5'], ['#e6e0d4', '#c9c2b4']], toits: [['#6d7480', '#555b66'], ['#d9b25a', '#b8913d']], styles: ['pierre', 'pierre', 'colombage'] },
    champs: ['lavande', 'ble'],
    decor: { herbe: [['bruyere', 5], ['fougere', 2], ['touffe', 2], ['eclat', 1], ['buisson', 2], ['buissonfleuri', 1]], sable: [['galet', 2], ['rocher', 1]], roche: [['mousse', 2], ['eclat', 2], ['rocher', 3]], neige: [['eclat', 1]] },
    vie: [['lievre', 2], ['mouton', 2], ['papillon', 2, ['#d7b8ff', '#ffffff']], ['poule', 1]],
    oiseaux: [['fou', 2], ['mouette', 1]],
    densite: .6, mousse: true,
  },
};
export const BIOME_IDS = Object.keys(BIOMES);
export const biomeDe = id => BIOMES[id] || BIOMES.prairie;
