# Le chemin : les noms français des objets. Les modèles sont nommés en anglais ; chacun de leurs mots a ici son nom
# français, dans le sens de l’objet : « can » est une canette, pas un verbe ; « cup » une tasse, pas une coupe sportive.
# Un mot du journal retrouve ainsi le nom de l’objet tel quel, sans passer par l’anglais. Voir sens.py.

# un mot d’étiquette anglais → ses mots français ; vide : le mot ne nomme rien
FR = {
  # la nature
  'tree': 'arbre', 'pine': 'sapin pin', 'palm': 'palmier', 'oak': 'chêne', 'fall': 'automne', 'autumn': 'automne', 'bush': 'buisson',
  'cactus': 'cactus', 'flower': 'fleur', 'grass': 'herbe', 'leafs': 'feuilles', 'mushroom': 'champignon', 'rock': 'rocher', 'rocks': 'rochers',
  'stone': 'pierre', 'stones': 'pierres', 'stump': 'souche', 'log': 'bûche tronc', 'logs': 'bûches', 'crops': 'cultures', 'crop': 'potager',
  'corn': 'maïs', 'wheat': 'blé', 'bamboo': 'bambou', 'lily': 'nénuphar', 'moss': 'mousse', 'plateau': 'acacia', 'trunk': 'tronc',
  'hedge': 'haie', 'plant': 'plante', 'potted': 'pot', 'sand': 'sable', 'snow': 'neige', 'snowflake': 'flocon', 'pile': 'tas',
  'blocks': '', 'cone': 'cône', 'fat': '', 'thin': '', 'dark': 'sombre', 'darkh': 'sombre', 'crooked': 'tordu', 'bend': 'courbé',
  'statue': 'statue', 'column': 'colonne', 'obelisk': 'obélisque', 'ring': 'anneau', 'head': 'tête', 'block': 'bloc', 'damaged': 'ruine',
  'campfire': 'feu', 'camp': 'camp', 'fire': 'feu', 'pit': 'foyer', 'bricks': 'briques', 'planks': 'planches', 'tent': 'tente',
  'canvas': 'toile', 'camping': 'camping', 'canoe': 'canoë', 'paddle': 'pagaie', 'bed': 'lit', 'sign': 'panneau', 'pot': 'pot',
  'fence': 'clôture barrière', 'gate': 'portail', 'doorway': 'porte', 'fortified': 'palissade', 'curved': '', 'diagonal': '', 'broken': 'cassé',
  # les maisons, la ville
  'building': 'bâtiment', 'house': 'maison', 'home': 'maison', 'shop': 'magasin boutique', 'store': 'magasin', 'skyscraper': 'gratte-ciel',
  'tower': 'tour', 'office': 'bureau', 'city': 'ville', 'planter': 'jardinière', 'parasol': 'parasol', 'fountain': 'fontaine',
  'lantern': 'lanterne', 'banner': 'bannière', 'stall': 'marché', 'cart': 'charrette', 'watermill': 'moulin', 'windmill': 'moulin',
  'wall': 'mur', 'market': 'marché', 'bakery': 'boulangerie', 'supermarket': 'supermarché', 'display': 'étalage', 'shelf': 'rayon',
  'shopping': 'courses', 'basket': 'panier', 'cash': 'caisse', 'register': '', 'freezer': 'congélateur', 'freezers': 'congélateur',
  'return': 'consigne', 'bags': 'sacs', 'boxes': 'boîtes', 'signpost': 'panneau', 'flag': 'drapeau', 'pennant': 'fanion',
  # les véhicules
  'train': 'train', 'locomotive': 'locomotive', 'carriage': 'wagon', 'wagon': 'wagon', 'tender': 'charbon', 'passenger': 'voyageurs',
  'diesel': 'locomotive', 'electric': 'électrique', 'bullet': 'tgv', 'subway': 'métro', 'metro': 'métro', 'tram': 'tramway', 'tramway': 'tramway',
  'container': 'conteneur', 'flatbed': 'wagon', 'coal': 'charbon', 'tank': 'citerne', 'lumber': 'bois', 'wood': 'bois', 'dirt': 'terre',
  'boat': 'bateau', 'ship': 'navire', 'sail': 'voilier', 'sailing': 'voile', 'row': 'barque', 'fishing': 'pêche', 'speed': 'vedette',
  'tug': 'remorqueur', 'tow': 'remorqueur', 'cargo': 'cargo', 'liner': 'paquebot', 'ocean': 'paquebot', 'ghost': 'fantôme', 'buoy': 'bouée',
  'medium': '', 'car': 'voiture', 'sedan': 'voiture berline', 'hatchback': 'voiture', 'suv': 'voiture', 'van': 'camionnette',
  'truck': 'camion', 'delivery': 'livraison camionnette', 'taxi': 'taxi', 'police': 'police', 'ambulance': 'ambulance', 'firetruck': 'pompiers',
  'garbage': 'poubelle', 'race': 'bolide', 'future': '', 'kart': 'karting', 'oobi': '', 'oodi': '', 'ooli': '', 'oopi': '', 'oozi': '',
  'tractor': 'tracteur', 'shovel': 'pelle', 'luxury': 'luxe', 'sports': 'sport', 'sled': 'luge traîneau',
  # les gens et les bêtes
  'character': 'personne', 'man': 'homme', 'male': 'homme', 'woman': 'femme', 'female': 'femme', 'aid': '', 'cane': 'canne',
  'blind': 'aveugle', 'vision': 'vue', 'crutch': 'béquille', 'glasses': 'lunettes', 'sunglasses': 'lunettes soleil', 'hearing': 'oreille',
  'wheelchair': 'fauteuil roulant', 'power': '', 'deluxe': '', 'animal': 'animal', 'beaver': 'castor', 'bee': 'abeille', 'bunny': 'lapin',
  'rabbit': 'lapin', 'cat': 'chat', 'chick': 'poussin', 'cow': 'vache', 'crab': 'crabe', 'deer': 'cerf chevreuil', 'dog': 'chien',
  'elephant': 'éléphant', 'fish': 'poisson', 'fox': 'renard', 'giraffe': 'girafe', 'hog': 'cochon', 'boar': 'sanglier', 'koala': 'koala',
  'lion': 'lion', 'monkey': 'singe', 'panda': 'panda', 'parrot': 'perroquet', 'penguin': 'manchot pingouin', 'pig': 'cochon',
  'polar': 'polaire', 'bear': 'ours', 'tiger': 'tigre', 'reindeer': 'renne',
  # la maison, dedans
  'kitchen': 'cuisine', 'bathroom': 'bain', 'cabinet': 'placard', 'table': 'table', 'chair': 'chaise', 'lounge': 'salon', 'sofa': 'canapé',
  'ottoman': 'pouf', 'relax': 'fauteuil', 'design': '', 'bench': 'banc', 'cushion': 'coussin', 'stool': 'tabouret', 'bar': 'comptoir',
  'bookcase': 'bibliothèque', 'library': 'bibliothèque', 'reading': 'lecture', 'books': 'livres', 'desk': 'bureau', 'drawer': 'tiroir',
  'drawers': 'tiroirs', 'lamp': 'lampe', 'ceiling': 'plafond', 'floor': '', 'fan': 'ventilateur', 'rug': 'tapis', 'doormat': 'paillasson',
  'bedroll': 'couchage duvet', 'bunk': 'superposé', 'television': 'télévision', 'antenna': 'antenne', 'vintage': '', 'radio': 'radio',
  'speaker': 'enceinte', 'computer': 'ordinateur', 'keyboard': 'clavier', 'mouse': 'souris', 'screen': 'écran', 'laptop': 'ordinateur portable',
  'mirror': 'miroir', 'sink': 'évier lavabo', 'shower': 'douche', 'bathtub': 'baignoire', 'toilet': 'toilettes', 'washer': 'lave-linge',
  'dryer': 'sèche-linge', 'stacked': '', 'fridge': 'frigo réfrigérateur', 'stove': 'cuisinière', 'microwave': 'micro-ondes',
  'blender': 'mixeur', 'toaster': 'grille-pain', 'hood': 'hotte', 'machine': 'machine', 'upper': '', 'built': '', 'in': '', 'trashcan': 'poubelle',
  'cardboard': 'carton', 'box': 'boîte', 'cloth': 'nappe', 'cross': '', 'coat': 'manteau', 'rack': 'portemanteau', 'frame': '',
  'standing': '', 'stand': '', 'doors': 'portes', 'glass': 'verre', 
  # les fêtes
  'christmas': 'noël', 'present': 'cadeau', 'wreath': 'couronne', 'snowman': 'bonhomme neige', 'nutcracker': 'casse-noisette', 'sock': 'chaussette',
  'lights': 'guirlande lumières', 'colored': '', 'decorated': 'décoré', 'gingerbread': 'biscuit', 'candy': 'bonbon', 'hat': 'chapeau',
  'bunker': 'rempart', 'birthday': 'anniversaire', 'cube': '', 'rectangle': '', 'triangle': '', 'hanging': 'suspendu', 'stack': 'tas', 'stick': 'bâtonnet',
  # la survie, les outils
  'workbench': 'établi atelier', 'anvil': 'enclume', 'grind': 'meule', 'tool': 'outil', 'barrel': 'tonneau', 'chest': 'coffre trésor',
  'crate': 'caisse', 'bucket': 'seau', 'packed': '', 'group': '', 'tan': '',
  # la cuisine, les aliments
  'food': 'nourriture', 'fruit': 'fruit', 'vegetable': 'légume', 'vegetables': 'légumes', 'apple': 'pomme', 'banana': 'banane', 'pear': 'poire',
  'cherries': 'cerises', 'grapes': 'raisin', 'lemon': 'citron', 'orange': 'orange', 'pineapple': 'ananas', 'strawberry': 'fraise',
  'watermelon': 'pastèque', 'melon': 'melon', 'coconut': 'noix-de-coco coco', 'avocado': 'avocat', 'advocado': 'avocat', 'carrot': 'carotte',
  'broccoli': 'brocoli', 'cabbage': 'chou', 'cauliflower': 'chou-fleur', 'celery': 'céleri', 'eggplant': 'aubergine', 'leek': 'poireau',
  'onion': 'oignon', 'paprika': 'poivron', 'pepper': 'poivre', 'pumpkin': 'citrouille', 'radish': 'radis', 'beet': 'betterave', 'turnip': 'navet',
  'tomato': 'tomate', 'salad': 'salade', 'bread': 'pain', 'loaf': 'pain', 'baguette': 'baguette', 'croissant': 'croissant', 'cake': 'gâteau',
  'cupcake': 'gâteau', 'muffin': 'muffin', 'cookie': 'biscuit cookie', 'donut': 'beignet', 'pancakes': 'crêpes', 'waffle': 'gaufre',
  'pie': 'tarte', 'mincemeat': 'tarte', 'pudding': 'flan', 'sundae': 'glace', 'ice': 'glace', 'cream': 'crème', 'cne': 'cornet',
  'scoop': 'boule', 'popsicle': 'glace esquimau', 'chocolate': 'chocolat', 'lollypop': 'sucette bonbon', 'honey': 'miel', 'butter': 'beurre',
  'peanut': 'cacahuète', 'whipped': 'chantilly', 'sprinkles': '', 'cheese': 'fromage', 'egg': 'œuf', 'meat': 'viande', 'cooked': 'cuit',
  'raw': 'cru', 'patty': 'steak', 'ribs': 'côtes', 'tenderizer': 'attendrisseur', 'sausage': 'saucisse', 'bacon': 'lard bacon', 'ham': 'jambon',
  'whole': '', 'wholer': '', 'turkey': 'dinde', 'salmon': 'saumon', 'mussel': 'moule', 'roe': 'œufs', 'sushi': 'sushi',
  'maki': 'sushi', 'rice': 'riz', 'ball': 'boule', 'soy': 'soja', 'burger': 'hamburger burger', 'fries': 'frites', 'hot': '', 'pizza': 'pizza',
  'taco': 'taco', 'sandwich': 'sandwich', 'sub': 'sandwich', 'chinese': 'nouilles', 'dim': '', 'sum': 'raviolis', 'sauerkraut': 'choucroute',
  'soup': 'soupe', 'broth': 'bouillon', 'stew': 'ragoût', 'cereal': 'céréales', 'tajine': 'plat marmite', 'skewer': 'brochette', 'slice': 'tranche',
  'cut': '', 'ketchup': 'ketchup', 'musterd': 'moutarde', 'mustard': 'moutarde', 'oil': 'huile', 'salt': 'sel', 'shaker': 'salière',
  'mill': 'moulin', 'cocktail': 'cocktail', 'coffee': 'café', 'tea': 'thé', 'wine': 'vin', 'white': 'blanc', 'soda': 'soda', 'frappe': 'café', 'frappuccino': 'café',
  'bottle': 'bouteille', 'bottles': 'bouteilles', 'can': 'canette conserve', 'crushed': 'écrasé', 'carton': 'brique lait', 'cup': 'tasse',
  'mug': 'tasse', 'saucer': 'soucoupe', 'plate': 'assiette', 'deep': 'creux', 'dinner': 'dîner', 'bowl': 'bol', 'pan': 'poêle casserole',
  'frying': 'poêle', 'lid': 'couvercle', 'spoon': 'cuillère', 'utensil': 'couvert', 'cooking': 'cuisine', 'whisk': 'fouet', 'mortar': 'mortier',
  'pestle': 'pilon', 'rolling': '', 'pin': 'rouleau', 'board': 'planche', 'cutting': 'découper', 'cutter': 'découpoir', 'japanese': 'japonais',
  'steamer': 'cuiseur vapeur', 'styrofoam': 'barquette', 'bag': 'sac', 'ginger': 'gingembre', 'mint': 'menthe', 
  # les couleurs : elles précisent, sans nommer
  'red': 'rouge', 'green': 'vert', 'blue': 'bleu', 'yellow': 'jaune', 'purple': 'violet', '1x': '', '2x': '', '3x': '',
}
# des objets dont le nom, mot à mot, tromperait : leurs mots français en entier
NOMS = {
  r'food-kit/hot-dog': 'hot-dog saucisse', r'food-kit/corn-dog': 'saucisse beignet', r'food-kit/dim-sum': 'raviolis vapeur',
  r'food-kit/rollingPin': 'rouleau pâtisserie', r'food-kit/rice-ball': 'riz boulette', r'food-kit/peanut-butter': 'cacahuète beurre',
  r'food-kit/ice-cream': 'glace cornet', r'food-kit/whipped-cream': 'chantilly crème', r'food-kit/egg-cup': 'coquetier œuf',
  r'food-kit/cup-saucer': 'tasse soucoupe', r'food-kit/maki-roe': 'sushi', r'food-kit/styrofoam-dinner': 'barquette repas',
  r'food-kit/bag': 'sac courses', r'food-kit/soda-can': 'canette soda', r'food-kit/can(-small)?$': 'conserve boîte', r'food-kit/mortar': 'mortier pilon',
  r'food-kit/ginger-bread-cutter': 'emporte-pièce biscuit', r'food-kit/ginger-bread': 'pain-d’épices biscuit', r'food-kit/pizza-cutter': 'roulette pizza',
  r'food-kit/cutting-board': 'planche découper', r'food-kit/carton': 'lait', r'furniture-kit/books$': 'livre', r'food-kit/chinese': 'nouilles boîte',
  r'nature-kit/bed': 'lit feuilles', r'nature-kit/pot_': 'jarre poterie', r'nature-kit/hanging_moss': 'mousse lichen',
  r'nature-kit/statue_ring': 'anneau pierre', r'nature-kit/statue_block': 'statue pierre', r'nature-kit/statue_head': 'statue tête',
  r'nature-kit/statue_column': 'colonne ruine', r'nature-kit/sign': 'panneau pancarte', r'nature-kit/canoe$': 'canoë barque',
  r'furniture-kit/bear': 'ours peluche nounours', r'furniture-kit/cabinetBed': 'chevet', r'furniture-kit/sideTable': 'guéridon table',
  r'furniture-kit/tableCoffee': 'table salon', r'furniture-kit/tableCloth': 'table nappe', r'furniture-kit/tableCross': 'table',
  r'furniture-kit/coatRack': 'portemanteau manteau', r'furniture-kit/loungeSofaOttoman': 'pouf', r'furniture-kit/loungeChair': 'fauteuil',
  r'furniture-kit/loungeDesignChair': 'fauteuil', r'furniture-kit/chairDesk': 'chaise bureau', r'furniture-kit/lampSquareCeiling': 'plafonnier lampe',
  r'furniture-kit/lamp(Round|Square)Floor': 'lampadaire lampe', r'furniture-kit/lampWall': 'applique lampe', r'furniture-kit/ceilingFan': 'ventilateur',
  r'furniture-kit/kitchenBar': 'comptoir cuisine', r'furniture-kit/stoolBar': 'tabouret', r'furniture-kit/kitchenCoffeeMachine': 'cafetière café',
  r'furniture-kit/bathroomSink': 'lavabo', r'furniture-kit/kitchenSink': 'évier cuisine', r'furniture-kit/bathroomMirror': 'miroir',
  r'furniture-kit/bathroomCabinet': 'armoire toilette', r'furniture-kit/kitchenCabinet': 'placard cuisine', r'furniture-kit/rugDoormat': 'paillasson',
  r'furniture-kit/bedBunk': 'lit superposé', r'furniture-kit/benchCushion': 'banquette coussin', r'furniture-kit/pottedPlant': 'plante pot',
  r'furniture-kit/plantSmall': 'plante pot', r'furniture-kit/washerDryerStacked': 'lave-linge sèche-linge', r'furniture-kit/cardboardBox': 'carton déménagement',
  r'furniture-kit/speaker': 'enceinte musique', r'furniture-kit/televisionAntenna': 'télévision antenne',
  r'mini-market/bottle-return': 'consigne bouteilles', r'mini-market/cash-register': 'caisse', r'mini-market/display-bread': 'pain boulangerie',
  r'mini-market/display-fruit': 'fruits marché', r'mini-market/shopping-cart': 'chariot courses', r'mini-market/shopping-basket': 'panier courses',
  r'mini-market/shelf': 'rayon supermarché', r'mini-characters/aid-cane-blind': 'canne aveugle', r'mini-characters/aid-cane-low-vision': 'canne aveugle',
  r'mini-characters/aid-cane$': 'canne', r'mini-characters/aid_hearing': 'appareil oreille', r'mini-characters/aid-glasses': 'lunettes',
  r'mini-characters/aid-sunglasses': 'lunettes soleil', r'mini-characters/aid-crutch': 'béquille',
  r'car-kit/garbage-truck': 'benne poubelle camion', r'car-kit/firetruck': 'camion pompiers', r'car-kit/tractor-police': 'tracteur',
  r'car-kit/tractor-shovel': 'pelle tracteur', r'car-kit/race': 'bolide voiture', r'car-kit/police': 'voiture police',
  r'car-kit/delivery': 'camionnette livraison', r'car-kit/kart': 'karting',
  r'train-kit/train-electric-bullet': 'tgv train', r'train-kit/train-carriage-tank': 'wagon citerne', r'train-kit/train-carriage-coal': 'wagon charbon',
  r'train-kit/train-carriage-container': 'wagon conteneur', r'train-kit/train-carriage-dirt': 'wagon terre', r'train-kit/train-carriage-(lumber|wood)': 'wagon bois',
  r'holiday-kit/train-tender': 'train jouet', r'holiday-kit/train': 'train jouet', r'holiday-kit/candy-cane': 'sucre-d’orge bonbon',
  r'holiday-kit/gingerbread': 'pain-d’épices bonhomme', r'holiday-kit/tree-decorated': 'sapin noël', r'holiday-kit/tree-snow': 'sapin neige',
  r'holiday-kit/lights': 'guirlande lumières', r'holiday-kit/snow-bunker': 'neige rempart', r'holiday-kit/snow-pile': 'neige tas',
  r'holiday-kit/snow-flat': 'neige', r'holiday-kit/sock': 'chaussette noël', r'holiday-kit/bench': 'banc', r'holiday-kit/lantern': 'lanterne',
  r'watercraft-kit/boat-fan': 'bateau marais', r'watercraft-kit/boat-house': 'péniche', r'watercraft-kit/boat-speed': 'vedette hors-bord',
  r'watercraft-kit/boat-fishing': 'bateau pêche', r'watercraft-kit/boat-sail': 'voilier', r'watercraft-kit/boat-row': 'barque',
  r'watercraft-kit/boat-(tug|tow)': 'remorqueur', r'watercraft-kit/ship-ocean-liner': 'paquebot', r'watercraft-kit/ship-cargo': 'cargo navire',
  r'watercraft-kit/ship-small-ghost': 'navire fantôme', r'watercraft-kit/buoy': 'bouée', r'pirate-kit/ship': 'navire voilier',
  r'pirate-kit/boat-row': 'barque', r'pirate-kit/flag': 'drapeau', r'pirate-kit/tool-paddle': 'pagaie rame',
  r'survival-kit/bedroll': 'couchage duvet', r'survival-kit/tent-canvas': 'tente toile', r'survival-kit/campfire-fishing-stand': 'feu poisson',
  r'survival-kit/campfire': 'feu camp', r'survival-kit/fence-doorway': 'palissade porte', r'survival-kit/fence-fortified': 'palissade',
  r'survival-kit/signpost': 'panneau poteau', r'survival-kit/tree-log': 'bûche tronc', r'survival-kit/tool-shovel': 'pelle',
  r'survival-kit/workbench-anvil': 'enclume forge', r'survival-kit/workbench-grind': 'meule atelier', r'survival-kit/box': 'caisse',
  r'fantasy-town-kit/stall-bench': 'marché banc', r'fantasy-town-kit/stall-stool': 'marché tabouret', r'fantasy-town-kit/cart-high': 'charrette',
  r'fantasy-town-kit/watermill': 'moulin eau', r'fantasy-town-kit/windmill': 'moulin vent', r'fantasy-town-kit/hedge-.*gate': 'haie portail',
  r'fantasy-town-kit/fence-gate': 'barrière portail', r'city-kit-suburban/planter': 'jardinière fleurs', r'city-kit-suburban/fence': 'clôture',
  r'city-kit-commercial/detail-parasol': 'parasol terrasse', r'cube-pets/animal-polar': 'ours blanc', r'cube-pets/animal-hog': 'sanglier cochon',
  r'cube-pets/animal-chick': 'poussin poule',
}
# les mots français qui précisent sans nommer : ils comptent peu
NUANCES_FR = set('rouge vert bleu jaune violet blanc sombre cassé écrasé creux cru cuit tordu courbé suspendu décoré cône électrique luxe sport'.split())
