# Le chemin : les noms français des objets. Les modèles sont nommés en anglais ; chacun de leurs mots a ici son nom
# français, dans le sens de l’objet : « can » est une canette, pas un verbe ; « cup » une tasse, pas une coupe sportive.
# Un mot du journal retrouve ainsi le nom de l’objet tel quel, sans passer par l’anglais. Voir sens.py.

# un mot d’étiquette anglais → ses mots français ; vide : le mot ne nomme rien
FR = {
  # la nature
  'tree': 'arbre', 'pine': 'sapin pin', 'palm': 'palmier', 'oak': 'chêne', 'fall': 'automne', 'autumn': 'automne', 'bush': 'buisson',
  'cactus': 'cactus', 'flower': 'fleur', 'grass': 'herbe', 'leafs': 'feuilles', 'mushroom': 'champignon', 'rock': 'rocher', 'rocks': 'rochers',
  'stone': 'pierre', 'stones': 'pierres', 'stump': 'souche', 'log': 'bûche tronc', 'logs': 'bûches', 'crops': 'cultures', 'crop': 'potager',
  'corn': 'maïs', 'wheat': 'blé', 'bamboo': 'bambou', 'lily': 'nénuphar', 'moss': 'mousse', 'plateau': 'acacia', 'trunk': 'tronc',
  'hedge': 'haie', 'plant': 'plante', 'potted': 'pot', 'sand': 'sable', 'snow': 'neige', 'snowflake': 'flocon', 'pile': 'tas',
  'blocks': '', 'cone': 'cône', 'fat': '', 'thin': '', 'dark': 'sombre', 'darkh': 'sombre', 'crooked': 'tordu', 'bend': 'courbé',
  'statue': 'statue', 'column': 'colonne', 'obelisk': 'obélisque', 'ring': 'anneau', 'head': 'tête', 'block': 'bloc', 'damaged': 'ruine',
  'campfire': 'feu', 'camp': 'camp', 'fire': 'feu', 'pit': 'foyer', 'bricks': 'briques', 'planks': 'planches', 'tent': 'tente',
  'canvas': 'toile', 'camping': 'camping', 'canoe': 'canoë', 'paddle': 'pagaie', 'bed': 'lit', 'sign': 'panneau', 'pot': 'pot',
  'fence': 'clôture barrière', 'gate': 'portail', 'doorway': 'porte', 'fortified': 'palissade', 'curved': '', 'diagonal': '', 'broken': 'cassé',
  # les maisons, la ville
  'building': 'bâtiment', 'house': 'maison', 'home': 'maison', 'shop': 'magasin boutique', 'store': 'magasin', 'skyscraper': 'gratte-ciel',
  'tower': 'tour', 'office': 'bureau', 'city': 'ville', 'planter': 'jardinière', 'parasol': 'parasol', 'fountain': 'fontaine',
  'lantern': 'lanterne', 'banner': 'bannière', 'stall': 'marché', 'cart': 'charrette', 'watermill': 'moulin', 'windmill': 'moulin',
  'wall': 'mur', 'market': 'marché', 'bakery': 'boulangerie', 'supermarket': 'supermarché', 'display': 'étalage', 'shelf': 'rayon',
  'shopping': 'courses', 'basket': 'panier', 'cash': 'caisse', 'register': '', 'freezer': 'congélateur', 'freezers': 'congélateur',
  'return': 'consigne', 'bags': 'sacs', 'boxes': 'boîtes', 'signpost': 'panneau', 'flag': 'drapeau', 'pennant': 'fanion',
  # les véhicules
  'train': 'train', 'locomotive': 'locomotive', 'carriage': 'wagon', 'wagon': 'wagon', 'tender': 'charbon', 'passenger': 'voyageurs',
  'diesel': 'locomotive', 'electric': 'électrique', 'bullet': 'tgv', 'subway': 'métro', 'metro': 'métro', 'tram': 'tramway', 'tramway': 'tramway',
  'container': 'conteneur', 'flatbed': 'wagon', 'coal': 'charbon', 'tank': 'citerne', 'lumber': 'bois', 'wood': 'bois', 'dirt': 'terre',
  'boat': 'bateau', 'ship': 'navire', 'sail': 'voilier', 'sailing': 'voile', 'row': 'barque', 'fishing': 'pêche', 'speed': 'vedette',
  'tug': 'remorqueur', 'tow': 'remorqueur', 'cargo': 'cargo', 'liner': 'paquebot', 'ocean': 'paquebot', 'ghost': 'fantôme', 'buoy': 'bouée',
  'medium': '', 'car': 'voiture', 'sedan': 'voiture berline', 'hatchback': 'voiture', 'suv': 'voiture', 'van': 'camionnette',
  'truck': 'camion', 'delivery': 'livraison camionnette', 'taxi': 'taxi', 'police': 'police', 'ambulance': 'ambulance', 'firetruck': 'pompiers',
  'garbage': 'poubelle', 'race': 'bolide', 'future': '', 'kart': 'karting', 'oobi': '', 'oodi': '', 'ooli': '', 'oopi': '', 'oozi': '',
  'tractor': 'tracteur', 'shovel': 'pelle', 'luxury': 'luxe', 'sports': 'sport', 'sled': 'luge traîneau',
  # les gens et les bêtes
  'character': 'personne', 'man': 'homme', 'male': 'homme', 'woman': 'femme', 'female': 'femme', 'aid': '', 'cane': 'canne',
  'blind': 'aveugle', 'vision': 'vue', 'crutch': 'béquille', 'glasses': 'lunettes', 'sunglasses': 'lunettes soleil', 'hearing': 'oreille',
  'wheelchair': 'fauteuil roulant', 'power': '', 'deluxe': '', 'animal': 'animal', 'beaver': 'castor', 'bee': 'abeille', 'bunny': 'lapin',
  'rabbit': 'lapin', 'cat': 'chat', 'chick': 'poussin', 'cow': 'vache', 'crab': 'crabe', 'deer': 'cerf chevreuil', 'dog': 'chien',
  'elephant': 'éléphant', 'fish': 'poisson', 'fox': 'renard', 'giraffe': 'girafe', 'hog': 'cochon', 'boar': 'sanglier', 'koala': 'koala',
  'lion': 'lion', 'monkey': 'singe', 'panda': 'panda', 'parrot': 'perroquet', 'penguin': 'manchot pingouin', 'pig': 'cochon',
  'polar': 'polaire', 'bear': 'ours', 'tiger': 'tigre', 'reindeer': 'renne',
  # la maison, dedans
  'kitchen': 'cuisine', 'bathroom': 'bain', 'cabinet': 'placard', 'table': 'table', 'chair': 'chaise', 'lounge': 'salon', 'sofa': 'canapé',
  'ottoman': 'pouf', 'relax': 'fauteuil', 'design': '', 'bench': 'banc', 'cushion': 'coussin', 'stool': 'tabouret', 'bar': 'comptoir',
  'bookcase': 'bibliothèque', 'library': 'bibliothèque', 'reading': 'lecture', 'books': 'livres', 'desk': 'bureau', 'drawer': 'tiroir',
  'drawers': 'tiroirs', 'lamp': 'lampe', 'ceiling': 'plafond', 'floor': '', 'fan': 'ventilateur', 'rug': 'tapis', 'doormat': 'paillasson',
  'bedroll': 'couchage duvet', 'bunk': 'superposé', 'television': 'télévision', 'antenna': 'antenne', 'vintage': '', 'radio': 'radio',
  'speaker': 'enceinte', 'computer': 'ordinateur', 'keyboard': 'clavier', 'mouse': 'souris', 'screen': 'écran', 'laptop': 'ordinateur portable',
  'mirror': 'miroir', 'sink': 'évier lavabo', 'shower': 'douche', 'bathtub': 'baignoire', 'toilet': 'toilettes', 'washer': 'lave-linge',
  'dryer': 'sèche-linge', 'stacked': '', 'fridge': 'frigo réfrigérateur', 'stove': 'cuisinière', 'microwave': 'micro-ondes',
  'blender': 'mixeur', 'toaster': 'grille-pain', 'hood': 'hotte', 'machine': 'machine', 'upper': '', 'built': '', 'in': '', 'trashcan': 'poubelle',
  'cardboard': 'carton', 'box': 'boîte', 'cloth': 'nappe', 'cross': '', 'coat': 'manteau', 'rack': 'portemanteau', 'frame': '',
  'standing': '', 'stand': '', 'doors': 'portes', 'glass': 'verre', 
  # les fêtes
  'christmas': 'noël', 'present': 'cadeau', 'wreath': 'couronne', 'snowman': 'bonhomme neige', 'nutcracker': 'casse-noisette', 'sock': 'chaussette',
  'lights': 'guirlande lumières', 'colored': '', 'decorated': 'décoré', 'gingerbread': 'biscuit', 'candy': 'bonbon', 'hat': 'chapeau',
  'bunker': 'rempart', 'birthday': 'anniversaire', 'cube': '', 'rectangle': '', 'triangle': '', 'hanging': 'suspendu', 'stack': 'tas', 'stick': 'bâtonnet',
  # la survie, les outils
  'workbench': 'établi atelier', 'anvil': 'enclume', 'grind': 'meule', 'tool': 'outil', 'barrel': 'tonneau', 'chest': 'coffre trésor',
  'crate': 'caisse', 'bucket': 'seau', 'packed': '', 'group': '', 'tan': '',
  # la cuisine, les aliments
  'food': 'nourriture', 'fruit': 'fruit', 'vegetable': 'légume', 'vegetables': 'légumes', 'apple': 'pomme', 'banana': 'banane', 'pear': 'poire',
  'cherries': 'cerises', 'grapes': 'raisin', 'lemon': 'citron', 'orange': 'orange', 'pineapple': 'ananas', 'strawberry': 'fraise',
  'watermelon': 'pastèque', 'melon': 'melon', 'coconut': 'noix-de-coco coco', 'avocado': 'avocat', 'advocado': 'avocat', 'carrot': 'carotte',
  'broccoli': 'brocoli', 'cabbage': 'chou', 'cauliflower': 'chou-fleur', 'celery': 'céleri', 'eggplant': 'aubergine', 'leek': 'poireau',
  'onion': 'oignon', 'paprika': 'poivron', 'pepper': 'poivre', 'pumpkin': 'citrouille', 'radish': 'radis', 'beet': 'betterave', 'turnip': 'navet',
  'tomato': 'tomate', 'salad': 'salade', 'bread': 'pain', 'loaf': 'pain', 'baguette': 'baguette', 'croissant': 'croissant', 'cake': 'gâteau',
  'cupcake': 'gâteau', 'muffin': 'muffin', 'cookie': 'biscuit cookie', 'donut': 'beignet', 'pancakes': 'crêpes', 'waffle': 'gaufre',
  'pie': 'tarte', 'mincemeat': 'tarte', 'pudding': 'flan', 'sundae': 'glace', 'ice': 'glace', 'cream': 'crème', 'cne': 'cornet',
  'scoop': 'boule', 'popsicle': 'glace esquimau', 'chocolate': 'chocolat', 'lollypop': 'sucette bonbon', 'honey': 'miel', 'butter': 'beurre',
  'peanut': 'cacahuète', 'whipped': 'chantilly', 'sprinkles': '', 'cheese': 'fromage', 'egg': 'œuf', 'meat': 'viande', 'cooked': 'cuit',
  'raw': 'cru', 'patty': 'steak', 'ribs': 'côtes', 'tenderizer': 'attendrisseur', 'sausage': 'saucisse', 'bacon': 'lard bacon', 'ham': 'jambon',
  'whole': '', 'wholer': '', 'turkey': 'dinde', 'salmon': 'saumon', 'mussel': 'moule', 'roe': 'œufs', 'sushi': 'sushi',
  'maki': 'sushi', 'rice': 'riz', 'ball': 'boule', 'soy': 'soja', 'burger': 'hamburger burger', 'fries': 'frites', 'hot': '', 'pizza': 'pizza',
  'taco': 'taco', 'sandwich': 'sandwich', 'sub': 'sandwich', 'chinese': 'nouilles', 'dim': '', 'sum': 'raviolis', 'sauerkraut': 'choucroute',
  'soup': 'soupe', 'broth': 'bouillon', 'stew': 'ragoût', 'cereal': 'céréales', 'tajine': 'plat marmite', 'skewer': 'brochette', 'slice': 'tranche',
  'cut': '', 'ketchup': 'ketchup', 'musterd': 'moutarde', 'mustard': 'moutarde', 'oil': 'huile', 'salt': 'sel', 'shaker': 'salière',
  'mill': 'moulin', 'cocktail': 'cocktail', 'coffee': 'café', 'tea': 'thé', 'wine': 'vin', 'white': 'blanc', 'soda': 'soda', 'frappe': 'café', 'frappuccino': 'café',
  'bottle': 'bouteille', 'bottles': 'bouteilles', 'can': 'canette conserve', 'crushed': 'écrasé', 'carton': 'brique lait', 'cup': 'tasse',
  'mug': 'tasse', 'saucer': 'soucoupe', 'plate': 'assiette', 'deep': 'creux', 'dinner': 'dîner', 'bowl': 'bol', 'pan': 'poêle casserole',
  'frying': 'poêle', 'lid': 'couvercle', 'spoon': 'cuillère', 'utensil': 'couvert', 'cooking': 'cuisine', 'whisk': 'fouet', 'mortar': 'mortier',
  'pestle': 'pilon', 'rolling': '', 'pin': 'rouleau', 'board': 'planche', 'cutting': 'découper', 'cutter': 'découpoir', 'japanese': 'japonais',
  'steamer': 'cuiseur vapeur', 'styrofoam': 'barquette', 'bag': 'sac', 'ginger': 'gingembre', 'mint': 'menthe', 
  # les couleurs : elles précisent, sans nommer
  'red': 'rouge', 'green': 'vert', 'blue': 'bleu', 'yellow': 'jaune', 'purple': 'violet', '1x': '', '2x': '', '3x': '',
}
# des objets dont le nom, mot à mot, tromperait : leurs mots français en entier
NOMS = {
  r'food-kit/hot-dog': 'hot-dog saucisse', r'food-kit/corn-dog': 'saucisse beignet', r'food-kit/dim-sum': 'raviolis vapeur',
  r'food-kit/rollingPin': 'rouleau pâtisserie', r'food-kit/rice-ball': 'riz boulette', r'food-kit/peanut-butter': 'cacahuète beurre',
  r'food-kit/ice-cream': 'glace cornet', r'food-kit/whipped-cream': 'chantilly crème', r'food-kit/egg-cup': 'coquetier œuf',
  r'food-kit/cup-saucer': 'tasse soucoupe', r'food-kit/maki-roe': 'sushi', r'food-kit/styrofoam-dinner': 'barquette repas',
  r'food-kit/bag': 'sac courses', r'food-kit/soda-can': 'canette soda', r'food-kit/can(-small)?$': 'conserve boîte', r'food-kit/mortar': 'mortier pilon',
  r'food-kit/ginger-bread-cutter': 'moule biscuit', r'food-kit/ginger-bread': 'pain-d’épices biscuit', r'food-kit/pizza-cutter': 'roulette pizza',
  r'food-kit/cutting-board': 'planche découper', r'food-kit/carton': 'lait', r'furniture-kit/books$': 'livre', r'food-kit/chinese': 'nouilles boîte',
  r'nature-kit/bed': 'lit feuilles', r'nature-kit/pot_': 'jarre poterie', r'nature-kit/hanging_moss': 'mousse lichen',
  r'nature-kit/statue_ring': 'anneau pierre', r'nature-kit/statue_block': 'statue pierre', r'nature-kit/statue_head': 'statue tête',
  r'nature-kit/statue_column': 'colonne ruine', r'nature-kit/sign': 'panneau pancarte', r'nature-kit/canoe$': 'canoë barque',
  r'furniture-kit/bear': 'ours peluche nounours', r'furniture-kit/cabinetBed': 'chevet', r'furniture-kit/sideTable': 'guéridon table',
  r'furniture-kit/tableCoffee': 'table salon', r'furniture-kit/tableCloth': 'table nappe', r'furniture-kit/tableCross': 'table',
  r'furniture-kit/coatRack': 'portemanteau manteau', r'furniture-kit/loungeSofaOttoman': 'pouf', r'furniture-kit/loungeChair': 'fauteuil',
  r'furniture-kit/loungeDesignChair': 'fauteuil', r'furniture-kit/chairDesk': 'chaise bureau', r'furniture-kit/lampSquareCeiling': 'plafonnier lampe',
  r'furniture-kit/lamp(Round|Square)Floor': 'lampadaire lampe', r'furniture-kit/lampWall': 'applique lampe', r'furniture-kit/ceilingFan': 'ventilateur',
  r'furniture-kit/kitchenBar': 'comptoir cuisine', r'furniture-kit/stoolBar': 'tabouret', r'furniture-kit/kitchenCoffeeMachine': 'cafetière café',
  r'furniture-kit/bathroomSink': 'lavabo', r'furniture-kit/kitchenSink': 'évier cuisine', r'furniture-kit/bathroomMirror': 'miroir',
  r'furniture-kit/bathroomCabinet': 'armoire toilette', r'furniture-kit/kitchenCabinet': 'placard cuisine', r'furniture-kit/rugDoormat': 'paillasson',
  r'furniture-kit/bedBunk': 'lit superposé', r'furniture-kit/benchCushion': 'banquette coussin', r'furniture-kit/pottedPlant': 'plante pot',
  r'furniture-kit/plantSmall': 'plante pot', r'furniture-kit/washerDryerStacked': 'lave-linge sèche-linge', r'furniture-kit/cardboardBox': 'carton déménagement',
  r'furniture-kit/speaker': 'enceinte musique', r'furniture-kit/televisionAntenna': 'télévision antenne',
  r'mini-market/bottle-return': 'consigne bouteilles', r'mini-market/cash-register': 'caisse', r'mini-market/display-bread': 'pain boulangerie',
  r'mini-market/display-fruit': 'fruits marché', r'mini-market/shopping-cart': 'chariot courses', r'mini-market/shopping-basket': 'panier courses',
  r'mini-market/shelf': 'rayon supermarché', r'mini-characters/aid-cane-blind': 'canne aveugle', r'mini-characters/aid-cane-low-vision': 'canne aveugle',
  r'mini-characters/aid-cane$': 'canne', r'mini-characters/aid_hearing': 'appareil oreille', r'mini-characters/aid-glasses': 'lunettes',
  r'mini-characters/aid-sunglasses': 'lunettes soleil', r'mini-characters/aid-crutch': 'béquille',
  r'car-kit/garbage-truck': 'benne poubelle camion', r'car-kit/firetruck': 'camion pompiers', r'car-kit/tractor-police': 'tracteur',
  r'car-kit/tractor-shovel': 'pelle tracteur', r'car-kit/race': 'bolide voiture', r'car-kit/police': 'voiture police',
  r'car-kit/delivery': 'camionnette livraison', r'car-kit/kart': 'karting',
  r'train-kit/train-electric-bullet': 'tgv train', r'train-kit/train-carriage-tank': 'wagon citerne', r'train-kit/train-carriage-coal': 'wagon charbon',
  r'train-kit/train-carriage-container': 'wagon conteneur', r'train-kit/train-carriage-dirt': 'wagon terre', r'train-kit/train-carriage-(lumber|wood)': 'wagon bois',
  r'holiday-kit/train-tender': 'train jouet', r'holiday-kit/train': 'train jouet', r'holiday-kit/candy-cane': 'sucre-d’orge bonbon',
  r'holiday-kit/gingerbread': 'pain-d’épices bonhomme', r'holiday-kit/tree-decorated': 'sapin noël', r'holiday-kit/tree-snow': 'sapin neige',
  r'holiday-kit/lights': 'guirlande lumières', r'holiday-kit/snow-bunker': 'neige rempart', r'holiday-kit/snow-pile': 'neige tas',
  r'holiday-kit/snow-flat': 'neige', r'holiday-kit/sock': 'chaussette noël', r'holiday-kit/bench': 'banc', r'holiday-kit/lantern': 'lanterne',
  r'watercraft-kit/boat-fan': 'bateau marais', r'watercraft-kit/boat-house': 'péniche', r'watercraft-kit/boat-speed': 'vedette hors-bord',
  r'watercraft-kit/boat-fishing': 'bateau pêche', r'watercraft-kit/boat-sail': 'voilier', r'watercraft-kit/boat-row': 'barque',
  r'watercraft-kit/boat-(tug|tow)': 'remorqueur', r'watercraft-kit/ship-ocean-liner': 'paquebot', r'watercraft-kit/ship-cargo': 'cargo navire',
  r'watercraft-kit/ship-small-ghost': 'navire fantôme', r'watercraft-kit/buoy': 'bouée', r'pirate-kit/ship': 'navire voilier',
  r'pirate-kit/boat-row': 'barque', r'pirate-kit/flag': 'drapeau', r'pirate-kit/tool-paddle': 'pagaie rame',
  r'survival-kit/bedroll': 'couchage duvet', r'survival-kit/tent-canvas': 'tente toile', r'survival-kit/campfire-fishing-stand': 'feu poisson',
  r'survival-kit/campfire': 'feu camp', r'survival-kit/fence-doorway': 'palissade porte', r'survival-kit/fence-fortified': 'palissade',
  r'survival-kit/signpost': 'panneau poteau', r'survival-kit/tree-log': 'bûche tronc', r'survival-kit/tool-shovel': 'pelle',
  r'survival-kit/workbench-anvil': 'enclume forge', r'survival-kit/workbench-grind': 'meule atelier', r'survival-kit/box': 'caisse',
  r'fantasy-town-kit/stall-bench': 'marché banc', r'fantasy-town-kit/stall-stool': 'marché tabouret', r'fantasy-town-kit/cart-high': 'charrette',
  r'fantasy-town-kit/watermill': 'moulin eau', r'fantasy-town-kit/windmill': 'moulin vent', r'fantasy-town-kit/hedge-.*gate': 'haie portail',
  r'fantasy-town-kit/fence-gate': 'barrière portail', r'city-kit-suburban/planter': 'jardinière fleurs', r'city-kit-suburban/fence': 'clôture',
  r'city-kit-commercial/detail-parasol': 'parasol terrasse', r'cube-pets/animal-polar': 'ours blanc', r'cube-pets/animal-hog': 'sanglier cochon',
  r'cube-pets/animal-chick': 'poussin poule',
}
# les mots français qui précisent sans nommer : ils comptent peu
NUANCES_FR = set('rouge vert bleu jaune violet blanc sombre cassé écrasé creux cru cuit tordu courbé suspendu décoré cône électrique luxe sport'.split())

# Les autres collections : KayKit, Quaternius, OpenGameArt
FR.update({
  'acacia': 'acacia', 'acaccia': 'acacia', 'umbreall': 'acacia', 'africa': 'afrique', 'african': 'afrique', 'af': '', 'air': '', 'alien': 'extraterrestre martien',
  'anchor': 'ancre', 'apatosaurus': 'diplodocus dinosaure', 'arcade': 'arcade jeu', 'arch': 'arche', 'armchair': 'fauteuil', 'astronaut': 'astronaute cosmonaute',
  'backpack': 'sac randonnée', 'balcony': 'balcon', 'bandages': 'pansement', 'bank': 'banque', 'bare': 'nu', 'bars': 'lingots', 'base': '', 'basemodule': 'base',
  'basketball': 'ballon basket', 'battery': 'pile batterie', 'beach': 'plage', 'bell': 'cloche', 'berries': 'baies', 'big': '', 'billboard': 'panneau affiche',
  'birch': 'bouleau', 'bird': 'oiseau', 'blacksmith': 'forge forgeron', 'boabab': 'baobab', 'bonfire': 'feu camp', 'book': 'livre', 'bookshelf': 'bibliothèque étagère',
  'boy': 'garçon', 'bridge': 'pont', 'brown': '', 'candle': 'bougie', 'candles': 'bougies', 'candycane': 'sucre-d’orge', 'carrots': 'carottes', 'case': 'étagère',
  'castle': 'château', 'casual': '', 'cecropia': 'arbre', 'chain': 'chaîne', 'chandelier': 'lustre', 'checkers': 'damier', 'cheeseburger': 'hamburger',
  'chef': 'cuisinier', 'chicken': 'poulet', 'chimney': 'cheminée', 'chunks': 'morceaux', 'church': 'église', 'ciaba': 'arbre', 'circus': 'cirque chapiteau',
  'civic': 'palais', 'claw': 'pince', 'closet': 'armoire placard', 'cloud': 'nuage', 'coaster': 'manège', 'cog': 'engrenage', 'coin': 'pièce monnaie', 'color': '',
  'comicbook': 'bd album', 'comicbooks': 'bd albums', 'common': '', 'compass': 'boussole', 'complete': '', 'containers': 'conteneurs', 'copal': 'arbre',
  'corndog': 'saucisse beignet', 'couch': 'canapé', 'covered': '', 'cowboy': 'cowboy', 'craft': 'vaisseau', 'crystals': 'cristaux', 'curtains': 'rideaux',
  'cushioned': 'coussin', 'cuttingboard': 'planche', 'dance': 'danse', 'dead': 'mort', 'defense': 'défense', 'destroyed': 'ruine', 'dish': 'vaisselle',
  'dishrack': 'égouttoir', 'dock': 'ponton quai', 'doctor': 'médecin', 'dolphin': 'dauphin', 'domino': 'domino', 'door': 'porte', 'drill': 'forage',
  'drinks': 'boissons', 'dumpster': 'benne poubelle', 'eagle': 'aigle', 'ear': '', 'elf': 'elfe', 'empty': '', 'entrance': 'entrée', 'farmstead': 'grenier',
  'firehydrant': 'borne incendie', 'fireplace': 'cheminée', 'first': '', 'flax': 'lin', 'flowers': 'fleurs', 'football': 'ballon football', 'footstool': 'tabouret',
  'fortress': 'forteresse', 'fried': 'frit', 'front': '', 'fuel': 'carburant', 'ful': '', 'full': 'plein', 'gable': '', 'game': 'jeu', 'gamer': 'joueur', 'garage': 'garage',
  'gas': 'essence', 'generic': '', 'girl': 'fille', 'gold': 'or', 'grain': 'grenier', 'grand': '', 'grey': '', 'guitar': 'guitare', 'hard': '', 'heart': 'cœur',
  'helmet': 'casque', 'hills': 'collines', 'hockey': 'hockey', 'horse': 'cheval', 'hospital': 'hôpital', 'hotdog': 'hot-dog saucisse', 'hourglass': 'sablier',
  'houseplant': 'plante', 'hut': 'cabane paillote', 'idol': 'statuette idole', 'information': 'information', 'ingredient': '', 'instantcamera': 'appareil-photo',
  'jackolantern': 'citrouille halloween', 'jar': 'bocal', 'jerrycan': 'jerrican bidon', 'jetty': 'ponton jetée', 'jewel': 'bijou diamant', 'jungle': 'jungle',
  'kelp': 'algue', 'kennel': 'abri', 'key': 'clé', 'kimono': 'kimono', 'king': '', 'kit': '', 'knight': 'chevalier', 'ladder': 'échelle', 'lander': 'vaisseau',
  'landscape': '', 'leg': '', 'lettuce': 'salade laitue', 'lifeboat': 'canot sauvetage', 'light': 'lampe', 'lilypad': 'nénuphar', 'llama': 'lama',
  'lock': 'cadenas', 'lumbermill': 'scierie', 'mahogany': 'acajou', 'mali': '', 'manta': 'raie', 'match': 'allumette', 'matchbox': 'allumettes', 'mayo': 'mayonnaise',
  'meeple': 'pion', 'melted': 'fondue', 'menu': 'menu', 'merchant': 'marchand', 'meteor': 'météorite', 'milk': 'lait', 'mine': 'mine', 'miner': 'mineur',
  'mining': 'mine', 'mistletoe': 'gui', 'monster': 'monstre', 'monument': 'monument', 'mountain': 'montagne', 'multi': '', 'nest': 'nid', 'night': 'chevet',
  'nigiri': 'sushi', 'ninja': 'ninja', 'nuggets': 'pépites', 'octopus': 'poulpe', 'oldclassy': '', 'oval': '', 'oven': 'four', 'pair': '', 'pallet': 'palette',
  'pancake': 'crêpe', 'panel': 'panneau', 'paper': 'papier', 'papertowel': 'rouleau', 'parasaurolophus': 'dinosaure', 'park': 'parc', 'parts': 'pièces',
  'pawn': 'pion', 'phila': 'plante', 'phone': 'téléphone portable', 'picture': 'photo', 'pictureframe': 'cadre tableau', 'pillow': 'coussin oreiller',
  'pillows': 'coussins', 'pinball': 'flipper', 'pipe': 'tuyau', 'piranha': 'piranha', 'pirate': 'pirate', 'plates': 'assiettes', 'plushie': 'peluche doudou',
  'pole': 'poteau', 'post': 'poteau', 'potato': 'patate', 'potatoes': 'patates', 'prize': 'loterie', 'propane': 'gaz', 'pug': 'carlin chien',
  'puzzlecube': 'cube jouet', 'pyramid': 'pyramide', 'queens': '', 'racer': 'bolide', 'raft': 'radeau', 'ray': 'raie', 'reeds': 'roseaux', 'reef': 'récif corail',
  'resource': '', 'roll': 'rouleau', 'rollerskate': 'patins roller', 'roof': 'toit', 'rover': 'véhicule', 'sack': 'sac', 'sashimi': 'sashimi poisson',
  'satellite': 'satellite', 'sauce': 'sauce', 'scaffolding': 'échafaudage', 'scorpion': 'scorpion', 'sea': 'mer', 'sentry': 'guet', 'set': '', 'shack': 'cabane',
  'shark': 'requin', 'sheep': 'mouton', 'shipping': '', 'shrine': 'autel', 'silver': 'argent', 'skate': 'skate', 'skateboard': 'skate planche', 'slim': '',
  'snowball': 'boule neige', 'solar': 'solaire', 'solarpanel': 'panneau solaire', 'sombrero': 'sombrero', 'spacetruck': 'véhicule', 'speeder': 'vaisseau',
  'spellbook': 'grimoire livre', 'sphere': 'boule', 'star': 'étoile', 'stationwagon': 'voiture break', 'steak': 'steak viande', 'stegosaurus': 'stégosaure dinosaure',
  'storehouse': 'grenier entrepôt', 'streetlight': 'lampadaire réverbère', 'stripes': '', 'structure': '', 'suit': 'costume', 'tavern': 'auberge taverne',
  'temple': 'temple', 'textiles': 'tissus étoffes', 'thorn': 'épineux', 'thornbush': 'buisson épineux', 'tile': '', 'toilets': 'toilettes', 'tomatoes': 'tomates',
  'torch': 'lampe torche', 'towel': 'serviette', 'trafficlight': 'feu circulation', 'trash': 'poubelle', 'trees': 'arbres', 'trex': 'tyrannosaure dinosaure',
  'triceratops': 'tricératops dinosaure', 'triple': '', 'tropic': 'tropical', 'tropical': 'tropical', 'umbrella': 'parapluie', 'vase': 'vase', 'vehicle': '',
  'velociraptor': 'vélociraptor dinosaure', 'vending': 'distributeur', 'viking': 'viking', 'washing': 'lave-linge', 'water': 'eau', 'waterbottle': 'gourde',
  'waterlily': 'nénuphar', 'watertower': 'château-d’eau', 'well': 'puits', 'whale': 'baleine', 'wheel': 'roue', 'wheelbarrow': 'brouette', 'willow': 'saule',
  'window': 'fenêtre', 'windturbine': 'éolienne', 'witch': 'sorcière', 'with': '', 'without': '', 'wizard': 'magicien sorcier', 'wolf': 'loup', 'wonder': 'merveille',
  'wooden': 'bois', 'woodstove': 'poêle bois', 'worker': 'ouvrier', 'wsail': 'voile', 'young': 'jeune', 'zebra': 'zèbre',
})
# des noms entiers, pour les modèles que le mot à mot trahirait, et pour les poses et les choses de l’archipel, nommées en français
NOMS.update({
  r'kaykit-city-builder-bits/building': 'immeuble maison ville', r'kaykit-city-builder-bits/car_police': 'voiture police', r'kaykit-city-builder-bits/car_taxi': 'taxi',
  r'kaykit-city-builder-bits/car_': 'voiture auto', r'kaykit-furniture-bits/book_set': 'livres', r'kaykit-furniture-bits/lamp_standing': 'lampadaire lampe',
  r'kaykit-furniture-bits/rug': 'tapis', r'kaykit-halloween-bits/candle_triple': 'bougies chandelier', r'kaykit-halloween-bits/post_lantern': 'lanterne réverbère',
  r'kaykit-halloween-bits/pumpkin\w*jackolantern': 'citrouille halloween', r'kaykit-halloween-bits/pumpkin': 'citrouille potiron', r'kaykit-halloween-bits/tree_dead': 'arbre mort',
  r'kaykit-halloween-bits/tree_pine': 'sapin automne', r'kaykit-halloween-bits/shrine': 'autel bougies', r'kaykit-holiday-bits/christmas_tree': 'sapin noël',
  r'kaykit-holiday-bits/chair_large': 'fauteuil', r'kaykit-holiday-bits/gingerbread_house': 'maison pain-d’épices', r'kaykit-holiday-bits/gingerbread_man': 'bonhomme pain-d’épices',
  r'kaykit-holiday-bits/hot_chocolate': 'chocolat chaud', r'kaykit-holiday-bits/present': 'cadeau', r'kaykit-holiday-bits/snowball_pile': 'boules neige',
  r'kaykit-holiday-bits/snowman': 'bonhomme neige', r'kaykit-holiday-bits/train': 'train jouet', r'kaykit-holiday-bits/wreath': 'couronne noël',
  r'kaykit-forest/Tree_Bare': 'arbre nu', r'kaykit-forest/Tree': 'arbre', r'kaykit-forest/Bush': 'buisson', r'kaykit-forest/Rock': 'rocher', r'kaykit-forest/Grass': 'herbe',
  r'kaykit-medieval/building_castle': 'château', r'kaykit-medieval/building_church': 'église', r'kaykit-medieval/building_home': 'maison', r'kaykit-medieval/building_tavern': 'auberge taverne',
  r'kaykit-medieval/building_market': 'marché', r'kaykit-medieval/building_mine': 'mine', r'kaykit-medieval/building_lumbermill': 'scierie',
  r'kaykit-medieval/building_watermill': 'moulin eau', r'kaykit-medieval/building_well': 'puits', r'kaykit-medieval/building_windmill': 'moulin vent',
  r'kaykit-medieval/building_blacksmith': 'forge forgeron', r'kaykit-medieval/building_tower': 'tour', r'kaykit-medieval/building_bridge': 'pont',
  r'kaykit-medieval/building_grain': 'grange', r'kaykit-medieval/building_destroyed': 'ruine', r'kaykit-medieval/building_scaffolding': 'échafaudage chantier',
  r'kaykit-medieval/cloud': 'nuage', r'kaykit-medieval/mountain': 'montagne', r'kaykit-medieval/hills': 'collines', r'kaykit-medieval/trees': 'bosquet arbres',
  r'kaykit-medieval/tree_single': 'arbre', r'kaykit-medieval/waterlily': 'nénuphar', r'kaykit-medieval/rock': 'rocher', r'kaykit-medieval/barrel': 'tonneau',
  r'kaykit-medieval/bucket': 'seau eau', r'kaykit-medieval/crate': 'caisse', r'kaykit-medieval/flag': 'drapeau', r'kaykit-medieval/ladder': 'échelle',
  r'kaykit-medieval/sack': 'sac', r'kaykit-medieval/tent': 'tente', r'kaykit-medieval/wheelbarrow': 'brouette', r'kaykit-medieval/resource_lumber': 'planches bois',
  r'kaykit-medieval/resource_stone': 'pierres', r'kaykit-medieval/pallet': 'palette',
  r'kaykit-mixed-bag-1/instantcamera_picture': 'photo photographie', r'kaykit-mixed-bag-1/instantcamera': 'appareil-photo photo', r'kaykit-mixed-bag-1/chain_anchor': 'ancre',
  r'kaykit-mixed-bag-1/chicken_plushie': 'peluche doudou', r'kaykit-mixed-bag-1/circus_tent': 'cirque chapiteau', r'kaykit-mixed-bag-1/comicbooks': 'bd albums',
  r'kaykit-mixed-bag-1/comicbook': 'bd album', r'kaykit-mixed-bag-1/mining_helmet': 'casque', r'kaykit-mixed-bag-1/puzzlecube': 'cube jouet',
  r'kaykit-mixed-bag-1/rollerskate': 'patins roller', r'kaykit-mixed-bag-1/umbrella': 'parapluie', r'kaykit-mixed-bag-1/waterbottle': 'gourde',
  r'kaykit-mixed-bag-1/woodstove': 'poêle bois', r'kaykit-mixed-bag-1/flax_flower': 'fleur', r'kaykit-mixed-bag-1/idol': 'statuette idole',
  r'kaykit-restaurant-bits/food_dinner': 'repas dîner', r'kaykit-restaurant-bits/food_stew': 'ragoût', r'kaykit-restaurant-bits/food_burger': 'hamburger',
  r'kaykit-restaurant-bits/fridge': 'frigo réfrigérateur', r'kaykit-restaurant-bits/stove': 'cuisinière', r'kaykit-restaurant-bits/pot_': 'marmite',
  r'kaykit-restaurant-bits/pan_': 'poêle', r'kaykit-restaurant-bits/crate_': 'cageot', r'kaykit-restaurant-bits/food_ingredient_potato': 'patate',
  r'kaykit-resource-bits/Gold_Bars': 'or lingots', r'kaykit-resource-bits/Silver_Bars': 'argent lingots', r'kaykit-resource-bits/Gold_Nuggets': 'pépites or',
  r'kaykit-resource-bits/Fuel_A_Barrel': 'baril', r'kaykit-resource-bits/Fuel_A_Jerrycan': 'jerrican bidon', r'kaykit-resource-bits/Pallet': 'palette',
  r'kaykit-resource-bits/Parts_Cog': 'engrenage', r'kaykit-resource-bits/Parts_Pile': 'ferraille', r'kaykit-resource-bits/Stone_Bricks': 'briques',
  r'kaykit-resource-bits/Stone_Chunks': 'pierres', r'kaykit-resource-bits/Textiles': 'tissus étoffes', r'kaykit-resource-bits/Wood_Log': 'bûches bois',
  r'kaykit-resource-bits/Wood_Planks': 'planches bois', r'kaykit-space-base-bits/basemodule': 'base spatiale', r'kaykit-space-base-bits/cargo': 'cargaison',
  r'kaykit-space-base-bits/containers': 'conteneurs', r'kaykit-space-base-bits/drill': 'forage', r'kaykit-space-base-bits/lander': 'vaisseau fusée',
  r'kaykit-space-base-bits/spacetruck': 'véhicule lunaire', r'kaykit-space-base-bits/windturbine': 'éolienne', r'kaykit-space-base-bits/structure': 'pylône',
  r'kaykit-board-game-bits/D(6|20)': 'dé dés', r'kaykit-board-game-bits/coin_10': 'pièces monnaie', r'kaykit-board-game-bits/coin': 'pièce or',
  r'kaykit-adventurers/mug': 'chope bière', r'kaykit-adventurers/spellbook': 'grimoire livre',
  r'space-kit/craft': 'vaisseau', r'space-kit/rover': 'véhicule lunaire', r'space-kit/satelliteDish': 'antenne parabole', r'space-kit/rock_crystals': 'cristaux',
  r'space-kit/desk_computerScreen': 'écran ordinateur', r'space-kit/desk_computer': 'ordinateur bureau', r'space-kit/desk_chair': 'chaise bureau',
  r'coaster-kit/stall-drinks': 'buvette boissons', r'coaster-kit/stall-food': 'stand nourriture', r'coaster-kit/stall-information': 'accueil information',
  r'coaster-kit/stall-toilets': 'toilettes', r'coaster-kit/park-entrance': 'parc attractions', r'coaster-kit/coaster': 'manège attraction',
  r'mini-arcade/air-hockey': 'hockey jeu', r'mini-arcade/arcade': 'jeu-vidéo arcade', r'mini-arcade/basketball': 'basket jeu', r'mini-arcade/cash': 'caisse',
  r'mini-arcade/claw': 'pince peluche', r'mini-arcade/dance': 'danse jeu', r'mini-arcade/prize': 'roue loterie', r'mini-arcade/vending': 'distributeur', r'mini-arcade/character': 'joueur',
  r'mini-skate/half-pipe': 'rampe skate', r'mini-skate/character-skate-boy': 'skateur garçon', r'mini-skate/character-skate-girl': 'skateur fille',
  r'racing-kit/raceCar': 'bolide', r'racing-kit/grandStand': 'tribune stade', r'racing-kit/flagCheckers': 'drapeau damier', r'racing-kit/billboard': 'panneau publicité',
  r'racing-kit/tent': 'tente', r'toy-car-kit/vehicle-monster': 'camion', r'toy-car-kit/vehicle-vintage': 'voiture ancienne', r'toy-car-kit/vehicle-truck': 'camion',
  r'toy-car-kit/vehicle-suv': 'voiture', r'city-kit-industrial/building': 'usine', r'city-kit-industrial/chimney': 'cheminée usine', r'city-kit-industrial/detail-tank': 'citerne',
  r'city-kit-industrial/shipping': 'conteneur', r'city-kit-industrial/solar': 'panneaux solaires', r'city-kit-industrial/water-tower': 'château-d’eau',
  r'city-kit-industrial/windmill': 'éolienne', r'platformer-kit/chest': 'coffre trésor', r'platformer-kit/coin': 'pièce or', r'platformer-kit/door': 'porte',
  r'platformer-kit/heart': 'cœur amour', r'platformer-kit/jewel': 'bijou diamant', r'platformer-kit/key': 'clé', r'platformer-kit/lock': 'cadenas',
  r'platformer-kit/sign': 'panneau', r'platformer-kit/star': 'étoile', r'platformer-kit/tree-snow': 'arbre neige', r'platformer-kit/tree-pine-snow': 'sapin neige',
  r'platformer-kit/barrel': 'tonneau', r'platformer-kit/crate': 'caisse', r'platformer-kit/flag': 'drapeau', r'platformer-kit/ladder': 'échelle',
  r'retro-urban-kit/truck': 'camion', r'retro-urban-kit/detail-bench': 'banc', r'retro-urban-kit/detail-dumpster': 'benne poubelle', r'retro-urban-kit/detail-light': 'lampadaire réverbère',
  r'retro-urban-kit/scaffolding': 'échafaudage chantier', r'retro-urban-kit/tree': 'arbre parc',
  r'q-food/ChickenLeg': 'poulet pilon', r'q-food/ChocolateBar': 'chocolat tablette', r'q-food/CookingPot_Soup': 'soupe marmite', r'q-food/CookingPot': 'marmite',
  r'q-food/KetchupMustard': 'ketchup moutarde', r'q-food/SoySauce': 'sauce soja', r'q-food/Sushi_NigiriOctopus': 'sushi poulpe', r'q-food/Sushi': 'sushi',
  r'q-food/PeanutButter': 'beurre cacahuète', r'q-food/Egg_Fried': 'œuf', r'q-food/Egg_Whole': 'œuf', r'q-food/Pepper': 'poivron', r'q-food/Bottle1': 'bouteille vin',
  r'q-food/IceCream': 'glace cornet', r'q-food/Popsicle': 'glace esquimau', r'q-food/Pancakes_Stack': 'crêpes', r'q-food/Hotdog': 'hot-dog saucisse',
  r'q-food/FryingPan': 'poêle', r'q-food/Jar_Large': 'bocal', r'q-food/DoubleCheeseburger': 'hamburger', r'q-food/BurgerLarge': 'hamburger',
  r'q-interior/Bathroom_Bathtub': 'baignoire bain', r'q-interior/Bathroom_Shower': 'douche', r'q-interior/Bathroom_Sink': 'lavabo', r'q-interior/Bathroom_ToiletPaper': 'toilettes',
  r'q-interior/Bathroom_Toilet': 'toilettes', r'q-interior/Bathroom_Towel': 'serviette', r'q-interior/Bathroom_WashingMachine': 'lave-linge machine-à-laver',
  r'q-interior/Bathroom_Mirror': 'miroir', r'q-interior/Bed_Bunk': 'lit superposé', r'q-interior/Bed_': 'lit', r'q-interior/Couch': 'canapé',
  r'q-interior/Curtains': 'rideaux fenêtre', r'q-interior/Door_Double': 'porte', r'q-interior/Drawer': 'commode tiroirs', r'q-interior/Houseplant': 'plante',
  r'q-interior/Kitchen_Fridge': 'frigo réfrigérateur', r'q-interior/Kitchen_Oven': 'four cuisinière', r'q-interior/Kitchen_Sink': 'évier', r'q-interior/Kitchen_Cabinet': 'placard cuisine',
  r'q-interior/Light_Chandelier': 'lustre', r'q-interior/Light_Desk': 'lampe bureau', r'q-interior/Light_Floor': 'lampadaire', r'q-interior/Light_Stand': 'lampadaire',
  r'q-interior/NightStand': 'table chevet', r'q-interior/Shelf': 'étagère', r'q-interior/Table_Round': 'table', r'q-interior/Trashcan': 'poubelle',
  r'q-furniture/BookCase': 'bibliothèque livres', r'q-furniture/CoffeeTable': 'table salon', r'q-furniture/Sofa': 'canapé',
  r'q-survival/FirstAidKit': 'trousse secours', r'q-survival/GasCan': 'jerrican essence', r'q-survival/PropaneTank': 'bouteille gaz', r'q-survival/WaterBottle': 'bouteille eau',
  r'q-survival/WoodLog': 'bûche bois', r'q-survival/WoodenTorch': 'torche flambeau', r'q-survival/Match_Fire': 'allumette', r'q-survival/Bonfire': 'feu camp',
  r'q-survival/Battery': 'pile batterie', r'q-survival/Can_': 'conserve boîte', r'q-survival/Compass': 'boussole', r'q-survival/Torch': 'lampe torche',
  r'q-buildings/Flat': 'immeuble appartement', r'q-buildings/House': 'maison', r'q-buildings/Shop': 'magasin boutique',
  r'textured-buildings/1Story_Sign': 'boutique magasin', r'textured-buildings/2Story_Sign': 'magasin boutique', r'textured-buildings/1Story': 'maison',
  r'textured-buildings/6Story': 'immeuble tour', r'textured-buildings/': 'immeuble ville',
  r'q-ships/BoatWSail': 'voilier', r'q-ships/CruiseShip': 'paquebot croisière', r'q-ships/Lifeboat': 'canot pneumatique', r'q-ships/Sail_ship': 'voilier trois-mâts',
  r'q-ships/Viking': 'drakkar viking', r'q-ships/Boat': 'barque bateau',
  r'q-desert/CactusWithSombrero': 'cactus sombrero mexique', r'q-desert/DeadTree': 'arbre mort', r'q-desert/(Big|Small)PalmTree': 'palmier oasis',
  r'q-crops/Apple': 'pommier', r'q-crops/Orange': 'oranger', r'q-crops/Bamboo': 'bambou', r'q-crops/Corn': 'maïs', r'q-crops/Wheat': 'blé', r'q-crops/Rice': 'riz rizière',
  r'q-crops/Pumpkin': 'citrouille', r'q-crops/Watermelon': 'pastèque', r'q-crops/Tomato': 'tomates', r'q-crops/Carrot': 'carottes potager', r'q-crops/Lettuce': 'salade potager',
  r'q-crops/BushBerries': 'groseilles baies', r'q-crops/Cactus': 'cactus', r'q-crops/PalmTree': 'palmier', r'q-crops/Mushroom': 'champignon', r'q-crops/Beet': 'betterave',
  r'q-nature/BirchTree': 'bouleau', r'q-nature/CommonTree': 'arbre', r'q-nature/PineTree': 'sapin pin', r'q-nature/Willow': 'saule', r'q-nature/CactusFlower': 'cactus fleur',
  r'q-nature/Rock_Moss': 'rocher mousse', r'q-nature/Rock_Snow': 'rocher neige', r'q-nature/TreeStump': 'souche', r'q-nature/WoodLog': 'bûche tronc',
  r'q-nature/BushBerries': 'baies buisson', r'q-nature/Bush': 'buisson', r'q-nature/Plant': 'plante',
  r'savane/AfricaTree': 'arbre afrique', r'savane/AfricanBoabab': 'baobab', r'savane/(acaccia|umbrella|umbreall)': 'acacia savane', r'savane/africanMahogany': 'acajou arbre',
  r'savane/africanThorn': 'épineux buisson', r'savane/(africaBush|yellowBush)': 'buisson brousse', r'savane/af_deadTree': 'branche',
  r'savane/(AfricanWheatGrass|africaGrass)': 'herbes savane', r'savane/waterReeds': 'roseaux', r'savane/Shack': 'cabane case', r'savane/Kennel': 'abri cabane',
  r'savane/PoleBuilding': 'hangar abri', r'savane/AfricaDock': 'ponton', r'savane/genericTree': 'arbre', r'savane/africaRock': 'rocher', r'savane/stoneGroup': 'pierres',
  r'tropiques/Bamboo': 'bambou', r'tropiques/Banana': 'bananier', r'tropiques/BeachPalm': 'palmier plage', r'tropiques/BirdNest': 'plante tropicale',
  r'tropiques/(Cecropia|Ciaba|Copal)': 'arbre jungle', r'tropiques/Coconut': 'noix-de-coco coco', r'tropiques/ElephantEar': 'plante tropicale',
  r'tropiques/JungleHut': 'paillote cabane', r'tropiques/Kelp': 'algue', r'tropiques/(Palm0|QueensPalm)': 'palmier cocotier', r'tropiques/ReefBase': 'récif corail',
  r'tropiques/SeaPlant': 'algues', r'tropiques/TropicFern': 'fougère', r'tropiques/Tropical_Jetty': 'ponton', r'tropiques/BeachGrass': 'herbe plage', r'tropiques/Phila': 'plante',
  r'mali/mali_house': 'maison terre', r'mali/mali_temple': 'mosquée', r'mali/mali_wonder': 'mosquée', r'mali/mali_market': 'marché souk', r'mali/mali_farmstead': 'grenier',
  r'mali/mali_(defense|sentry)_tower': 'tour', r'mali/mali_fortress': 'forteresse', r'mali/mali_library': 'bibliothèque', r'mali/mali_storehouse': 'grenier',
  r'mali/mali_civic': 'palais', r'maya/mayan': 'pyramide temple maya', r'maya/chinagong': 'gong chine', r'maya/merchant': 'tente marchand',
  r'archipel/bete-mouton': 'mouton brebis', r'archipel/bete-poule': 'poule', r'archipel/bete-crabe': 'crabe', r'archipel/bete-renard': 'renard', r'archipel/bete-lievre': 'lièvre',
  r'archipel/bete-rougegorge': 'oiseau passereau', r'archipel/bete-chat': 'chat', r'archipel/bete-chevreuil': 'chevreuil biche', r'archipel/oiseau-mouette': 'mouette',
  r'archipel/oiseau-goeland': 'goéland', r'archipel/oiseau-fou': 'oiseau', r'archipel/oiseau-fregate': 'frégate oiseau', r'archipel/oiseau-oie': 'oie',
  r'archipel/phare': 'phare', r'archipel/maison-volets': 'maison volets', r'archipel/maison': 'maison', r'archipel/pont': 'pont', r'archipel/banc': 'banc',
  r'archipel/puits': 'puits', r'archipel/feu': 'feu camp', r'archipel/nuage-orage': 'orage nuage', r'archipel/nuage-pluie': 'pluie nuage averse',
  r'archipel/etang': 'étang mare', r'archipel/fleurs': 'fleurs', r'archipel/arbre-fleuri': 'arbre fleuri cerisier', r'archipel/arbre-nu': 'arbre nu',
  r'archipel/cairn': 'cairn pierres', r'archipel/menhir': 'menhir', r'archipel/ronce': 'ronces', r'archipel/baies': 'baies',
  r'poses/dos-': 'dos', # une personne de dos
  # les pictos : ce que chaque emoji montre
  r'pictos/main$': 'main',
  r'pictos/doigt$': 'doigt',
  r'pictos/pied$': 'pied',
  r'pictos/jambe$': 'jambe',
  r'pictos/bras$': 'bras',
  r'pictos/yeux$': 'yeux',
  r'pictos/bouche$': 'bouche',
  r'pictos/nez$': 'nez',
  r'pictos/oreille$': 'oreille',
  r'pictos/dent$': 'dent',
  r'pictos/langue$': 'langue',
  r'pictos/cerveau$': 'cerveau',
  r'pictos/visage$': 'visage',
  r'pictos/traces$': 'traces',
  r'pictos/sang$': 'sang',
  r'pictos/bulle$': 'parole',
  r'pictos/pensee$': 'pensée',
  r'pictos/ampoule$': 'idée',
  r'pictos/question$': 'question',
  r'pictos/attention$': 'attention',
  r'pictos/porte-voix$': 'cri',
  r'pictos/chut$': 'silence',
  r'pictos/lettre$': 'lettre',
  r'pictos/micro$': 'micro',
  r'pictos/calendrier$': 'calendrier',
  r'pictos/horloge$': 'horloge',
  r'pictos/reveil$': 'réveil',
  r'pictos/globe$': 'monde',
  r'pictos/carte$': 'carte',
  r'pictos/valise$': 'valise',
  r'pictos/arc-en-ciel$': 'arc-en-ciel iris',
  r'pictos/etincelles$': 'magie',
  r'pictos/accord$': 'accord',
  r'pictos/balance$': 'justice',
  r'pictos/bague$': 'bague',
  r'pictos/colombe$': 'paix',
  r'pictos/priere$': 'prière',
  r'pictos/trophee$': 'victoire',
  r'pictos/medaille$': 'médaille',
  r'pictos/couronne$': 'couronne',
  r'pictos/bebe$': 'bébé',
  r'pictos/coeur-brise$': 'rupture',
  r'pictos/fete$': 'fête',
  r'pictos/robe$': 'robe',
  r'pictos/chemise$': 'chemise',
  r'pictos/pantalon$': 'pantalon',
  r'pictos/chaussure$': 'chaussure',
  r'pictos/gants$': 'gant',
  r'pictos/chapeau$': 'chapeau',
  r'pictos/echarpe$': 'écharpe',
  r'pictos/bottes$': 'botte',
  r'pictos/manteau$': 'manteau',
  r'pictos/stop$': 'stop',
  r'pictos/interdit$': 'interdit',
  r'pictos/erreur$': 'erreur',
  r'pictos/loupe$': 'loupe',
  r'pictos/theatre$': 'théâtre',
  r'pictos/cinema$': 'cinéma',
  r'pictos/palette$': 'couleurs',
  r'pictos/colere$': 'colère',
  r'pictos/honte$': 'honte',
  r'pictos/etonnement$': 'étonnement',
  r'pictos/inquietude$': 'inquiétude',
  r'pictos/doute$': 'doute',
  r'pictos/ennui$': 'ennui',
  r'pictos/folie$': 'folie',
  r'pictos/mensonge$': 'mensonge',
  r'poses/debout-chef-female': 'cuisinière chef cuisine', r'poses/debout-chef-male': 'cuisinier chef cuisine', r'poses/debout-doctor-female': 'médecin infirmière',
  r'poses/debout-doctor-male': 'médecin docteur', r'poses/debout-worker-female': 'ouvrière chantier', r'poses/debout-worker-male': 'ouvrier chantier maçon',
  r'poses/debout-suit-female': 'femme affaires bureau', r'poses/debout-suit-male': 'costume cravate patron', r'poses/debout-oldclassy-female': 'mamie mémé vieille',
  r'poses/debout-oldclassy-male': 'papi pépé vieux', r'poses/debout-cowboy': 'cowboy western', r'poses/debout-kimono': 'kimono japon japonais',
  r'poses/debout-pirate': 'pirate', r'poses/debout-viking': 'viking', r'poses/debout-ninja': 'ninja', r'poses/debout-witch': 'sorcière', r'poses/debout-wizard': 'magicien sorcier',
  r'poses/debout-elf': 'elfe lutin', r'poses/debout-knight': 'chevalier', r'poses/debout-casual.*female': 'femme fille', r'poses/debout-casual': 'homme garçon',
  r'poses/lit-': 'lire lecture livre roman', r'poses/marche-dog': 'chien promener', r'poses/marche-': 'marcher marche promenade balade', r'poses/course-cube': 'chien courir', r'poses/course-': 'courir course jogging',
  r'poses/saut-': 'sauter saut bondir', r'poses/ramasse-': 'ramasser cueillir', r'poses/porte-': 'porter carton déménager', r'poses/triste-': 'triste tristesse chagrin pleurer larmes',
  r'poses/joie-': 'joie heureux bonheur rire fête', r'poses/dort-': 'dormir sommeil sieste allongé', r'poses/assis-sol': 'assis asseoir repos', r'poses/assis-chaise': 'assis chaise attendre',
  r'poses/salue-': 'saluer salut adieu', r'poses/acclame-': 'applaudir acclamer applaudissements', r'poses/pompes-': 'sport pompes musculation',
  r'poses/peche-': 'pêcher pêche pêcheur', r'poses/creuse-': 'creuser bêcher jardiner jardinage', r'poses/bricole-': 'bricoler réparer bricolage',
  r'poses/rampe-': 'ramper', r'poses/lance-': 'lancer jeter', r'poses/accroupi-': 'accroupi cacher', r'poses/tombe-': 'tomber chute trébucher',
  r'poses/fauteuil-': 'fauteuil-roulant handicap', r'poses/nage-(homme|femme)': 'nager nage baignade natation', r'poses/danse-cube': 'danser danse',
  r'poses/danse-': 'danser danse bal', r'poses/mange-cube-cow': 'vache brouter', r'poses/mange-cube-pig': 'cochon manger', r'poses/mange-cube-bunny': 'lapin manger',
  r'poses/galop-': 'cheval galoper galop', r'poses/bete-cow': 'vache', r'poses/bete-horse': 'cheval jument', r'poses/bete-llama': 'lama alpaga', r'poses/bete-pig': 'cochon porc',
  r'poses/bete-pug': 'chien carlin', r'poses/bete-sheep': 'mouton brebis agneau', r'poses/bete-zebra': 'zèbre', r'poses/bete-chick': 'poussin', r'poses/bete-red-fox': 'renard',
  r'poses/bete-cat': 'chat', r'poses/bete-dog': 'chien', r'poses/bete-wolf': 'loup', r'poses/vol-bird': 'oiseau', r'poses/vol-eagle': 'aigle rapace',
  r'poses/nage-piranha': 'piranha', r'poses/nage-dolphin': 'dauphin', r'poses/nage-fish': 'poisson', r'poses/nage-manta': 'raie', r'poses/nage-shark': 'requin',
  r'poses/nage-whale': 'baleine', r'poses/dino-apatosaurus': 'diplodocus dinosaure', r'poses/dino-parasaurolophus': 'dinosaure', r'poses/dino-stegosaurus': 'stégosaure dinosaure',
  r'poses/dino-trex': 'tyrannosaure dinosaure', r'poses/dino-triceratops': 'tricératops dinosaure', r'poses/dino-velociraptor': 'vélociraptor dinosaure',
  r'q-transport/\w*Bicycle': 'vélo bicyclette', r'q-transport/Ambulance': 'ambulance', r'q-transport/SchoolBus': 'car scolaire bus école', r'q-transport/Bus': 'bus autobus',
  r'q-transport/Taxi': 'taxi', r'q-transport/TrafficCone': 'cône plot', r'q-transport/TrafficLight': 'feu circulation', r'q-transport/Train': 'train tramway',
  r'vehicules/avion-jouet': 'avion', r'vehicules/avion-leger': 'avion', r'vehicules/avion-ligne': 'avion ligne aéroport', r'vehicules/avion-papier': 'avion papier',
  r'vehicules/moto': 'moto motocyclette', r'vehicules/rgs-Firetruck': 'camion pompiers', r'vehicules/rgs-Limousine': 'limousine voiture', r'vehicules/rgs-Roadster': 'voiture décapotable',
  r'vehicules/rgs-Truck': 'camion remorque', r'vehicules/rgs-Van': 'camionnette fourgon',
  r'objets-oga/chameau': 'chameau dromadaire', r'objets-oga/chess_king': 'échecs roi', r'objets-oga/chess_knight': 'échecs cavalier', r'objets-oga/drumset': 'batterie tambour',
  r'objets-oga/ecole': 'école collège lycée', r'objets-oga/electric_guitar': 'guitare électrique', r'objets-oga/horseshoe': 'fer cheval', r'objets-oga/maison-comb': 'peigne',
  r'objets-oga/maison-cup': 'tasse', r'objets-oga/maison-pencil': 'crayon', r'objets-oga/maison-scissors': 'ciseaux', r'objets-oga/maison-toothbrush': 'brosse-à-dents',
  r'objets-oga/rake': 'râteau', r'objets-oga/stylo': 'stylo crayon écrire', r'objets-oga/teapot': 'théière thé', r'objets-oga/wine_glass': 'verre vin',
  r'quaternius-farm/(Big|Small|Open)?Barn': 'grange', r'quaternius-farm/ChickenCoop': 'poulailler poules', r'quaternius-farm/Silo_House': 'silo grange',
  r'quaternius-farm/Silo': 'silo', r'quaternius-farm/(Tower)?Windmill': 'moulin', r'quaternius-farm/WaterTower': 'réservoir eau', r'quaternius-farm/Well': 'puits',
  r'quaternius-farm/Fence': 'clôture barrière',
})
